Repository temp-portfolio-team/backend, pull requests merged in 2022-03, with the labels that each got.

#29 Feat : [Add] 회원 프로필 생성 및 수정 + 파일 업로드
  .gitignore
  build.gradle
  src/main/java/com/bob/mate/InitTest.java
  src/main/java/com/bob/mate/domain/post/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/bob/mate/domain/user/controller/OauthController.java
  src/main/java/com/bob/mate/domain/user/controller/ResourceController.java
  src/main/java/com/bob/mate/domain/user/controller/UserController.java
  src/main/java/com/bob/mate/domain/user/dto/LoginResponse.java
  src/main/java/com/bob/mate/domain/user/dto/RefreshTokenRequest.java
  src/main/java/com/bob/mate/domain/user/dto/UserProfileQueryDto.java
  src/main/java/com/bob/mate/domain/user/dto/UserProfileRequest.java
  src/main/java/com/bob/mate/domain/user/dto/UserProfileResponse.java
  src/main/java/com/bob/mate/domain/user/dto/UserResponse.java
  src/main/java/com/bob/mate/domain/user/entity/User.java
  src/main/java/com/bob/mate/domain/user/entity/UserProfile.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepository.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/bob/mate/domain/user/service/AuthService.java
  src/main/java/com/bob/mate/domain/user/service/OauthService.java
  src/main/java/com/bob/mate/domain/user/service/UserService.java
  src/main/java/com/bob/mate/global/audit/AuditListener.java
  src/main/java/com/bob/mate/global/config/WebMvcConfig.java
  src/main/java/com/bob/mate/global/config/WebSecurityConfig.java
  src/main/java/com/bob/mate/global/exception/ErrorCode.java
  src/main/java/com/bob/mate/global/jwt/AuthorizationExtractor.java
  src/main/java/com/bob/mate/global/test/UserDummy.java
  src/main/java/com/bob/mate/global/util/AuthenticationInterceptor.java
  src/main/java/com/bob/mate/global/util/file/FileStore.java
  src/main/java/com/bob/mate/global/util/file/UploadFile.java
  src/main/resources/application.yml
Labels: enhancement

#31 refactor: update get all posts logic, get one post logic
  src/main/java/com/bob/mate/domain/post/dto/AllPostResponse.java
  src/main/java/com/bob/mate/domain/post/dto/OnePostResponse.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepository.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/bob/mate/domain/post/service/PostService.java
  src/main/resources/data.sql
Labels: enhancement

#33 chore: update wrong codes
  src/main/java/com/bob/mate/domain/post/dto/AllPostResponse.java
  src/main/java/com/bob/mate/domain/post/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepositoryImpl.java
Labels: refactor

#34 chore: update codes
  .gitignore
  src/main/java/com/bob/mate/domain/chat/config/WebSocketConfig.java
  src/main/java/com/bob/mate/domain/chat/config/websocket/WebSocketConfig.java
  src/main/java/com/bob/mate/domain/chat/handler/ChatHandler.java
  src/main/java/com/bob/mate/domain/post/dto/AllPostResponse.java
  src/main/java/com/bob/mate/domain/post/dto/OnePostResponse.java
  src/main/java/com/bob/mate/domain/post/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepository.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/bob/mate/domain/post/service/PostService.java
  src/main/java/com/bob/mate/domain/user/entity/UploadFile.java
  src/main/java/com/bob/mate/domain/user/entity/User.java
  src/main/java/com/bob/mate/domain/user/entity/UserProfile.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/bob/mate/domain/user/service/UserService.java
  src/main/java/com/bob/mate/global/config/redis/RedisConfig.java
  src/main/java/com/bob/mate/global/util/file/FileStore.java
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: enhancement

#35 chore: update wrong codes
  src/main/java/com/bob/mate/domain/post/dto/OnePostResponse.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepositoryImpl.java
Labels: refactor

#36 chore: update codes
  src/main/java/com/bob/mate/domain/post/dto/OnePostResponse.java
  src/main/java/com/bob/mate/domain/post/repository/PostCustomRepositoryImpl.java
Labels: refactor

#37 chore: update wrong codes
  src/main/java/com/bob/mate/domain/post/dto/CommentResponse.java
  src/main/java/com/bob/mate/domain/post/repository/CommentCustomRepositoryImpl.java
Labels: refactor

#38 chore: update wrong codes
  src/main/java/com/bob/mate/domain/post/dto/CommentResponse.java
  src/main/java/com/bob/mate/domain/post/repository/CommentCustomRepositoryImpl.java
Labels: refactor

#41 feat: add get my posts, comments
  src/main/java/com/bob/mate/domain/post/dto/MyCommentResponse.java
  src/main/java/com/bob/mate/domain/post/dto/MyPostResponse.java
  src/main/java/com/bob/mate/domain/user/controller/UserController.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/bob/mate/domain/user/service/UserService.java
  src/main/java/com/bob/mate/global/config/WebMvcConfig.java
  src/main/java/com/bob/mate/global/config/WebSecurityConfig.java
Labels: enhancement, refactor

#43 Refactor : [Refactor] UserController 코드 리팩토링
  src/main/java/com/bob/mate/domain/post/entity/Post.java
  src/main/java/com/bob/mate/domain/user/controller/UserController.java
  src/main/java/com/bob/mate/domain/user/dto/UserResponse.java
  src/main/java/com/bob/mate/domain/user/service/AuthService.java
  src/main/java/com/bob/mate/domain/user/service/UserService.java
  src/main/java/com/bob/mate/global/config/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/bob/mate/global/config/filter/JwtAuthenticationFilter.java
Labels: refactor

#42 feat: add get my posts, comments
  src/main/java/com/bob/mate/domain/post/dto/MyCommentResponse.java
  src/main/java/com/bob/mate/domain/post/dto/MyPostResponse.java
  src/main/java/com/bob/mate/domain/post/entity/Post.java
  src/main/java/com/bob/mate/domain/user/controller/UserController.java
  src/main/java/com/bob/mate/domain/user/dto/UserResponse.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/bob/mate/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/bob/mate/domain/user/service/AuthService.java
  src/main/java/com/bob/mate/domain/user/service/UserService.java
  src/main/java/com/bob/mate/global/config/WebMvcConfig.java
  src/main/java/com/bob/mate/global/config/WebSecurityConfig.java
  src/main/java/com/bob/mate/global/config/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/bob/mate/global/config/filter/JwtAuthenticationFilter.java
Labels: enhancement

#44 Refactor : User 엔티티 CreateUser 생성 메서드 기본이미지 파일 이름 추가
  src/main/java/com/bob/mate/domain/user/dto/LoginResponse.java
  src/main/java/com/bob/mate/domain/user/entity/User.java
  src/main/java/com/bob/mate/domain/user/oauth/OauthAttributes.java
Labels: refactor

#45 Feat : [Add] JwtAuthenticationEntryPoint 구현
  src/main/java/com/bob/mate/domain/user/controller/OauthController.java
  src/main/java/com/bob/mate/global/config/WebSecurityConfig.java
  src/main/java/com/bob/mate/global/config/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/bob/mate/global/config/filter/JwtAuthenticationFilter.java
  src/main/java/com/bob/mate/global/config/filter/SendErrorResponse.java
  src/main/java/com/bob/mate/global/jwt/AuthorizationExtractor.java
  src/main/resources/application.yml
Labels: bug, enhancement, refactor

#46 feat: add aws s3 codes
  build.gradle
  src/main/java/com/bob/mate/domain/aws/controller/S3Controller.java
  src/main/java/com/bob/mate/domain/aws/service/S3Service.java
  src/main/java/com/bob/mate/global/config/aws/AmazonS3Config.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
Labels: enhancement

#48 Refactor : AWS S3 파일업로드 관련 로직 추가 및 변경
  .gitignore
  src/main/java/com/bob/mate/domain/aws/controller/S3Controller.java
  src/main/java/com/bob/mate/domain/aws/service/S3Service.java
  src/main/java/com/bob/mate/domain/user/controller/ResourceController.java
  src/main/java/com/bob/mate/domain/user/dto/UserProfileResponse.java
  src/main/java/com/bob/mate/domain/user/dto/UserResponse.java
  src/main/java/com/bob/mate/domain/user/entity/UploadFile.java
  src/main/java/com/bob/mate/domain/user/entity/User.java
  src/main/java/com/bob/mate/domain/user/oauth/OauthAttributes.java
  src/main/java/com/bob/mate/domain/user/service/UserService.java
  src/main/java/com/bob/mate/global/config/WebSecurityConfig.java
  src/main/java/com/bob/mate/global/config/provider/KakaoUserInfo.java
  src/main/java/com/bob/mate/global/util/file/FileStore.java
  src/main/resources/application.yml
Labels: enhancement, refactor

#50 [Refactor] Aws S3 파일 삭제, 기본이미지 설정
  src/main/java/com/bob/mate/domain/aws/service/S3Service.java
  src/main/java/com/bob/mate/domain/user/dto/UserProfileRequest.java
  src/main/java/com/bob/mate/domain/user/entity/UploadFile.java
  src/main/java/com/bob/mate/domain/user/entity/User.java
  src/main/java/com/bob/mate/domain/user/entity/UserProfile.java
  src/main/java/com/bob/mate/domain/user/service/UserService.java
  src/main/java/com/bob/mate/global/util/file/FileStore.java
  src/main/resources/application.yml
Labels: refactor
